twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - bootstrap_3_horizontal_layout.html.twig
        #- form_theme.html.twig

    globals:
        gmaps_key: '%env(GMAPS_KEY)%'

when@test:
    twig:
        strict_variables: true
